language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/wheelhouse
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y python-numpy libgdal1h gdal-bin
install:
  - "pip install -U pip"
  - "pip install --extra-index-url=https://dd8kvqd1c0bor.cloudfront.net/pxm -c https://mapbox-pi.s3.amazonaws.com/pxm/constraints.txt -r requirements-dev.txt"
  - "pip install --extra-index-url=https://dd8kvqd1c0bor.cloudfront.net/pxm -c https://mapbox-pi.s3.amazonaws.com/pxm/constraints.txt scipy"
  - "pip install --extra-index-url=https://dd8kvqd1c0bor.cloudfront.net/pxm -c https://mapbox-pi.s3.amazonaws.com/pxm/constraints.txt -r requirements.txt"
  - "pip install -e .[test]"
script:
  - py.test --cov rio_color --cov-report term-missing
after_success:
  - coveralls
